### ISSUE TITLE
scss插值语句 #{} 

### ISSUE THREAD

**Issue by Betty985** [Betty985/511#8]
[插值语句 #{}](https://www.sass.hk/docs/) (Interpolation: #{})
通过 #{} 插值语句可以在选择器或属性名中使用变量：

```scss
$name: foo;
$attr: border;
p.#{$name} {
  #{$attr}-color: blue;
}
```
